service: aws-serverless

provider:
    name: aws
    region: ${opt:region, 'us-east-1'}
    stage: ${opt:stage, 'dev'}
    runtime: provided.al2
    environment: ${file(./aws/environment.yml)}
    iamRoleStatements: 
        - ${file(./aws/iamRoles/dynamodb.yml)}

package:
    include:
        - public/index.php
    # Directories to exclude from deployment
    exclude:
        - .env
        - node_modules/**
        - resources/assets/**
        - storage/**
        - tests/**

custom: ${file(./aws/variables.yml)} 

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - serverless-s3-sync

resources:
  Resources:
    Assets: ${file(./aws/resources/assets.yml)}
    Cache: ${file(./aws/resources/dynamodb.yml)}


## yarn install https://www.serverless.com/plugins/serverless-s3-sync